### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by kellyrowland** [kellyrowland/ldo-deterministic#4]
@rachelslaybaugh 

I'm not really sure what to put as for the 3 - 5 keywords; I haven't been able to find the ones for the original LDO paper published in NSE.

**Comment by rachelslaybaugh** [comment]
how about

quadrature; lagrange; discrete ordinates; transport

?

**Comment by kellyrowland** [comment]
Sounds good to me, thanks. Posted the same issue over in the MC VR paper whenever you get to that one.
